name: Auto approve

on:
  pull_request_target:

permissions: write-all

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      app: ${{ secrets.RENOVATE_APP }}[bot]
    steps:
      - name: Get token
        id: get_token
        if: github.actor == env.app
        uses: tibdex/github-app-token@v2
        with:
          private_key: ${{ secrets.ACTION_APP_KEY }}
          app_id: ${{ secrets.ACTION_APP_ID }}

      - uses: hmarr/auto-approve-action@v3
        if: github.actor == env.app
        with:
          review-message: "🌟 LGTM"
          github-token: ${{ steps.get_token.outputs.token }}
