name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        run: yarn install

  publish:
    needs: [test]
    uses: ./.github/workflows/publish.yml
    if: github.ref == 'refs/heads/main'
    secrets: inherit
